language: python
python:
  - "2.7"

services: mysql

env:
  global:
    # - PDBlib="/home/travis/build/CATH-summer-2017/rootsite/tst/static/temppdbs"
    # - DJANGO_SETTINGS_MODULE="rootsite.settings"
    # - PYTHONPATH="/home/travis/build/CATH-summer-2017/django_CATH" 
before_install:
  - pip install Django==1.11.*
  - cp -r init ..
  - cd ../  
  - django-admin startproject rootsite
  - cat init/django_settings.py >> rootsite/rootsite/settings.py
  - cat init/django_urls.py >> rootsite/rootsite/urls.py


  - echo ~ ;
  - echo $PWD;
  # - tree rootsite ; ###tree is not installed
  # - pwd

install:
  - git clone https://github.com/CATH-summer-2017/django_CATH.git rootsite/tst
  - pip install -r rootsite/tst/requirements.txt
  # - pip install -r tst/requirements.txt

before_script:
  # - mysql -e 'create database django; create database test_django;'
  - mysql -e 'create database django; grant all privileges on django.* to 'travis'@'localhost';'
  - mysql -e 'create database test_django; grant all privileges on test_django.* to 'travis'@'localhost';'

  - cd rootsite
  - ./manage.py migrate tst 
  - echo PDBlib="$PWD/tst/static/temppdbs" #### this is easier

  - ./manage.py shell < tst/dbscript/initnodes.py
  - ./manage.py shell < tst/dbscript/struct2S.py
  - ./manage.py shell < tst/dbscript/S2H.py
  - ./manage.py dumpdata tst -o tst/fixtures/test_temp.json
  # - ./manage.py dumpdata tst -o

  - ./manage.py runserver 127.0.0.0:8001 &

script:
  - # do nothing;
  - ./manage.py test tst --keepdb
  # - wget http://localhost:8001/tst/test/
  # - wget http://localhost:8001/tst/domain/
  # - 
