language: python
python:
  - "2.7"

services: mysql

env:
  global:
    # - DJANGO_SETTINGS_MODULE="rootsite.settings"
    # - PYTHONPATH="/home/travis/build/shouldsee/django_CATH" 
before_install:
  - pip install Django==1.11.*
  - cp -r init ..
  - cd ../  
  - django-admin startproject rootsite
  - cat init/django_settings.py >> rootsite/rootsite/settings.py
  - cat init/django_urls.py >> rootsite/rootsite/urls.py

  # - pwd

install:
  - git clone https://github.com/CATH-summer-2017/django_CATH.git rootsite/tst
  - pip install -r rootsite/tst/requirements.txt
  # - pip install -r tst/requirements.txt

before_script:
  - mysql -e 'create database django;'
  - cd rootsite
  - ./manage.py runserver &

script:
  - # do nothing;
  - wget http://localhost:8000/tst/domain/
  # - 
