# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

levels=[ None,
'root',
'Class',
'arch',
'topo',
'homsf',
's35',
's60',
's95',
's100',
'domain_counter'];

letters = [None,
'R',
'C',
'A',
'T',
'H',
'S',
'O',
'L',
'I',
'D']

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias
    # version = apps.get_model("tst", "version")
    version = apps.get_model("tst", "version")

    version.objects.create(name = 'root').save()

    level = apps.get_model("tst", "level")

    # level.obejcts.using(db_alias).bulk_create(
    #     level(letter="")
    #     level()
    #     )
    for i,(lvl,letter) in enumerate( zip(levels,letters)):
        if i:
            l = level.objects.create(name=lvl, letter=letter, id=i )

    node = apps.get_model("tst", "classification")

    node.objects.using(db_alias).bulk_create([
    node(
    Class = 1,
    arch = 0,
    level_id = 2 ,
    version_id = 1,
    ),
    node(
    Class = 2,
    arch = 0,
    level_id = 2 ,
    version_id = 1,
    ),
    node(
    Class = 3,
    arch = 0,
    level_id = 2 ,
    version_id = 1,
    ),
    node(
    Class = 4,
    arch = 0,
    level_id = 2 ,
    version_id = 1,
    ),      

    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Country = apps.get_model("myapp", "Country")
    db_alias = schema_editor.connection.alias
    Country.objects.using(db_alias).filter(name="USA", code="us").delete()
    Country.objects.using(db_alias).filter(name="France", code="fr").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0002_make_tables'),
    ]
    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]