# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0003_init_meta'),
    ]

    operations = [

        migrations.CreateModel(
            name='HMMprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),               
                ('text', models.TextField(blank=True, null=True)),
                ('cath_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tst.classification')),
                # ('cath_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.classification')),
            ],
        ),
        migrations.CreateModel(
            name='HSPfrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=None)),
                ('end', models.IntegerField(default=None)),
                ('raw', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='seqDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('version', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc', models.CharField(db_index=True, max_length=10)),
                ('subversion', models.IntegerField(default=0)),
                ('length', models.IntegerField()),
                ('cath_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tst.classification')),
                ('seqDB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.seqDB')),
            ],
        ),



        migrations.AddField(
            model_name='hspfrag',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.sequence'),
        ),

        migrations.AddField(
            model_name='hmmprofile',
            name='length',
            field=models.IntegerField(default=None),
        ),

        # migrations.CreateModel(
        #     name='hit4hmm2hsp',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('start', models.IntegerField(default=None)),
        #         ('end', models.IntegerField(default=None)),
        #         ('logCevalue', models.FloatField(default=None)),
        #         ('logIevalue', models.FloatField(default=None)),
        #         ('bitscore', models.FloatField(default=None)),
        #         ('bias', models.FloatField(default=None)),
        #         ('acc_avg', models.FloatField(null=True)),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='hit4hmm2hsp',
        #     name='query',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.HMMprofile'),
        # ),
        # migrations.AddField(
        #     model_name='hit4hmm2hsp',
        #     name='target',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.sequence'),
        # ),
        # migrations.AddField(
        #     model_name='hmmprofile',
        #     name='hits',
        #     field=models.ManyToManyField(through='tst.hit4hmm2hsp', to='tst.sequence'),
        # ),


    ]
