# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0004_init_ISS'),
    ]

    operations = [



        migrations.CreateModel(
            name='hit4hmm2hsp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=None)),
                ('end', models.IntegerField(default=None)),
                ('logCevalue', models.FloatField(default=None)),
                ('logIevalue', models.FloatField(default=None)),
                ('bitscore', models.FloatField(default=None)),
                ('bias', models.FloatField(default=None)),
                ('acc_avg', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hit4hmm2hsp',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.HMMprofile'),
        ),
        migrations.AddField(
            model_name='hit4hmm2hsp',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.sequence'),
        ),
        
        migrations.AddField(
            model_name='hmmprofile',
            name='hits',
            field=models.ManyToManyField(through='tst.hit4hmm2hsp', to='tst.sequence'),
        ),



    ]
