# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0005_init_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='acc',
            field=models.CharField(db_index=True, max_length=12),
        ),
    ]
