# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0006_longer'),
    ]

    operations = [
        migrations.CreateModel(
            name='hit4cath2cath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISS_raw', models.IntegerField(default=None, null = True)),
                ('ISS_norm', models.FloatField(default=None, null = True )),
                ('node1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hit4cath2cath1', to='tst.classification')),
                ('node2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hit4cath2cath2', to='tst.classification')),
                ('seqDB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.seqDB')),
            ],
        ),
    ]
