# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0009_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit4cath2cath',
            name='hcount_geoavg',
            field=models.FloatField(default=None, null=True),
        ),
    ]
