# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0010_hcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='hit4hmm2hspPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoavg', models.FloatField(default=None)),
                ('overlap', models.IntegerField(default=None)),
                ('hit1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair1', to='tst.hit4hmm2hsp')),
                ('hit2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair2', to='tst.hit4hmm2hsp')),
                ('masked',models.BooleanField(default=False)),
            ],
        ),
    ]
